### ISSUE TITLE
Firefox to Chrome streaming is NOT working!

### ISSUE THREAD

**Issue by muaz-khan** [muaz-khan/WebRTC-Experiment#1]
Test this WebRTC Chrome to Firefox video conferencing demo. It works fine if Chrome Beta is OFFERER and Firefox Nightly is ANSWERER.

https://googledrive.com/host/0B6GWd_dUUTT8dW5ycGVPT0V1bTg/chrome-to-firefox.html

It fails if Firefox Nightly creates Offer-SDP and chrome beta tries to create Answer SDP.

Though, it gets remote stream  finely in both cases. But the blank stream in 2nd case!

Here is the source code:
https://github.com/muaz-khan/WebRTC-Experiment/tree/master/chrome-to-firefox

I think the original issue comes in this line:

https://github.com/muaz-khan/WebRTC-Experiment/blob/master/chrome-to-firefox/RTCPeerConnection-v1.4.js#L49

**Comment by mayos** [comment]
Dear Muaz,

This issue appears again with the latest PeerConnection.js, could you help ro resolve it?
