### ISSUE TITLE
How to get users to join streams in rooms automatically but only share their media on request in RTCMultiConnection?

### ISSUE THREAD

**Issue by tehXor** [muaz-khan/WebRTC-Experiment#199]
Currently I have video conferencing rooms set up with RTCMultiConnection like it is described in "Setup Video Conference using full syntax!".
What I would like to achieve now is that users in these rooms should see/hear the streams of others as soon as the other person opens the connection with connection.open() but should not start to stream their media as well instantly but only when they as will trigger connection.open() (or another function for that case). At the moment as soon as one person triggers connection.open() everybody gets all streams and starts to stream, too.

I couldn't find a way to configure this specific use case with the API (but maybe I've overlooked something).
Setting direction to "one-way" works like I want it but only as long as only one user would like to share his media. When a second user triggers connection.open() he sees his local stream as well as the remote stream of the first user but the stream seems to be ignored by the first user which is already broadcasting (so he doesn't see the second stream). "one-to-many" and "many-to-many" work like described above.

I've already got a setup like this to work with the broadcast experiment but RTCMultiConnection seems to be more powerful so I think it could be better if use that instead. I'm also sure it can be done by rewriting some functions but before I start spending time adjusting the library I thought I ask if there maybe is way doing this with the current API ;-)

Thanks a lot for any feedback (and of course this great library)!

**Comment by sunilcarpenter** [comment]
hi
when i  switch devices multiple time video response very slow  and streaming very slow  and delay
my code below
    connection.selectDevices(audioInputDevices.value);
    connection.selectDevices(videoOutputDevices.value);
     connection.removeStream({
       local: true,
    }, true); 
    connection.addStream({video : true, audio: true})

please sugest to me
