### ISSUE TITLE
Is it possible to switch sources (camera - screen) during conference with RTCMultiConnection 1.8

### ISSUE THREAD

**Issue by killmenot** [muaz-khan/WebRTC-Experiment#219]
Hi,

I have a system where users have a meeting and shares their camera streams with each others. We have a moment where we need one user to share their screen. Is it possible in the current version? And if yes, how can I achieve it?

**Comment by karthivcet11** [comment]
Hi,  I am using rtcmulticonnection.js for video call ,screen sharing and file sharing working fine, 
I want to implement the camera flip option during the video call meeting. Can you help me. 
I need code for same
