### ISSUE TITLE
[RecordRTC] How to improve resolution of recorded video?

### ISSUE THREAD

**Issue by diegoacuna** [muaz-khan/WebRTC-Experiment#233]
Hi, I'm using RecordRTC library to record the screen on the user (like in the demo page https://www.webrtc-experiment.com/RecordRTC/ with "Record Screen" checkbox checked) and when I set the width and height setting from both video and canvas the resolution of the recorded video is really bad. Is possible to improve the resolution of the recorded video to for example record a video in like hd quality?

**Comment by niteeshjoshi** [comment]
Hello sir,
As you said above, I change my minwidth and maxwidth but while opening in mobile, screen of mobile get increase in size. What would I do for that?
