### ISSUE TITLE
Sharing screen with Microsoft Word and Microsoft PPT does not work well

### ISSUE THREAD

**Issue by work-ouyang** [muaz-khan/WebRTC-Experiment#255]
I tried the screen sharing demo through the webrtc-experiment url
https://www.webrtc-experiment.com/RTCMultiConnection/screen-sharing.html
The testing environment : Chrome Version 36.0.1985.125 ,    10 users. 
The sharing screen does work well especially for PDF, Paint. However, when I tested sharing screen for microsoft word document, it does not work well. The document scrolling is not captured. 
For microsoft ppt, if I use the editing mode, the sharing screen works, but if I press "play" button in the ppt, the sharing screen does not work. 
Is there any solution? Thank you.

**Comment by roy2651** [comment]
@work-ouyang hey man， I aso meet  this problem。 I‘m working on it。have you some solutions？ please help me
