### ISSUE TITLE
help how to set my own ice server?

### ISSUE THREAD

**Issue by arivasvera** [muaz-khan/WebRTC-Experiment#305]
Hello, I am trying to set up my own ice server, but for some reason, the script always calls a iFrame where, for what I see loads its own ice servers.
This is what I'm doing:

/_RTCMultiConnection.js_/

//connection.getExternalIceServers = isChrome;
connection.getExternalIceServers = false;

var iceServers = [];

iceServers.push({
url: 'myturn:3478'
});

/*iceServers.push({
url: 'stun:stun.l.google.com:19302'
});

iceServers.push({
url: 'stun:stun.anyfirewall.com:3478'
});

iceServers.push({
url: 'turn:turn.bistri.com:80',
credential: 'homeo',
username: 'homeo'
});

iceServers.push({
url: 'turn:turn.anyfirewall.com:443?transport=tcp',
credential: 'webrtc',
username: 'webrtc'
});*/

connection.iceServers = iceServers;

Please tell me if what I'm doing wrong or missing something

**Comment by jam1401** [comment]
This worked for me in version 3

var iceServers = [];

iceServers.push({
url: 'turn:turnhost',
credential: 'test',
username: 'test'
});

window.RMCExternalIceServers = iceServers;

var connection = new RTCMultiConnection();

**Comment by arivasvera** [comment]
wow! two years later. thanks @jam1401 I'm closing this issue
