### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'optional' of false

### ISSUE THREAD

**Issue by danbuntu** [muaz-khan/WebRTC-Experiment#321]
Hi

I've followed the screensharing example at

http://www.rtcmulticonnection.org/docs/getting-started/

I've downloaded the lastest version of RTCMultiConnection.js and linked to that as the cdn doesn't seem to want to work for me.

When I click the open a room a room option in chrome the popup appears that lets me select the screen to share but then I get nothing. 

In the developer console I get the following error

Uncaught TypeError: Cannot assign to read only property 'optional' of false

**Comment by muaz-khan** [comment]
Fixed: https://github.com/muaz-khan/RTCMultiConnection/commit/55aeddfff4d651348ecb0785e5f3d4360cfafd7a

**Comment by danbuntu** [comment]
awesome that fixed it. Thanks for the quick fix
