### ISSUE TITLE
screen sharing android

### ISSUE THREAD

**Issue by lzago** [muaz-khan/WebRTC-Experiment#330]
hi,
i tested the screen sharing experiment on google Nexus 9 (Android 5.0), since i read the Android support on the Readme, but i doesn't work. And i am not surprised since on Android Chrome doesn't support extension. Is it a mistake on the Readme?

Regards,

**Comment by muaz-khan** [comment]
Screen capturing is currently NOT available in mobile devices, both using Chrome & Firefox. It maybe a typo mistake, however my main point was:

* You can capture screen from desktop (windows/mac/linux)
* You can **view the screen** in Android (Chrome/Firefox/Opera) or iOS

**Comment by lzago** [comment]
thanks a lot, it's clear now.
