### ISSUE TITLE
Very Best Possible  Video

### ISSUE THREAD

**Issue by milkandteamedia** [muaz-khan/WebRTC-Experiment#345]
Hi,
I'm using (https://github.com/muaz-khan/RTCMultiConnection/blob/master/demos/all-in-one.html) The All-In-One Demo to learn and explore.  
Where and how do I set the very best Video quality?

**Comment by muaz-khan** [comment]
First step: Capture full-HD media:

* http://www.rtcmulticonnection.org/docs/mediaConstraints/

Second step: Use `good-max/min-bitrate` attributes in the SDP descriptions before sharing with remote peers.

* [Low latency but smooth/high-quality audio and video](https://www.webrtc-experiment.com/RTCMultiConnection/audioconferencing.html#comment-1814390966)
* ["processSdp" can be used to override SDP](http://www.rtcmulticonnection.org/docs/processSdp/)
* [How to use processSdp & good-max/min-bitrate](https://github.com/muaz-khan/RTCMultiConnection/issues/23#issuecomment-66870920)

As [it is said](https://www.webrtc-experiment.com/webrtcpedia/#comment-1987201975), maximizing the bitrate usage will deliver better quality stream. [b=AS](http://www.rtcmulticonnection.org/docs/bandwidth/) can also help. There is optional `bandwidth` attribute for `webkitGetUserMedia` as well.

**Comment by zevarito** [comment]
@muaz-khan Do you know if `x-google` flags are interpreted at Chrome level or libjingle level? I wonder if those can be used when using Webrtc natively.
