### ISSUE TITLE
Problem record audio quality

### ISSUE THREAD

**Issue by vanbinh2811** [muaz-khan/WebRTC-Experiment#368]
Hello sir, I change 
multiStreamRecorder.canvas = {
                        width: video.width,
                        height: video.height
                    };
to resolution video record
multiStreamRecorder.canvas = {
                        width: resolution_x,
                        height: resolution_y
                    };
listen audio quality bad. help me
demo: http://jsfiddle.net/nvb1128/rmtsx1e5/

**Comment by muaz-khan** [comment]
Setting different `bufferSize` value can fix it.

```javascript
* From the spec: This value controls how frequently the audioprocess event is
* dispatched and how many sample-frames need to be processed each call.
* Lower values for buffer size will result in a lower (better) latency.
* Higher values will be necessary to avoid audio breakup and glitches
* The size of the buffer (in sample-frames) which needs to
* be processed each time onprocessaudio is called.
* Legal values are (256, 512, 1024, 2048, 4096, 8192, 16384).

multiStreamRecorder.bufferSize = 16384;
```

**Comment by vanbinh2811** [comment]
that work. Thank you for reply
