### ISSUE TITLE
help help~  Can I use WebRTC to iOS app without html?

### ISSUE THREAD

**Issue by shenguanjiejie** [muaz-khan/WebRTC-Experiment#414]
I'm not good at English :( , who handsome can tell me about this question....

**Comment by PoD-Stas** [comment]
Wat? Frankly speaking, I didn't get what do you mean.

(what language do you prefer? / какой язык предпочитаете?)

**Comment by muaz-khan** [comment]
**Yep**, you can write **native-iOS** applications (running top over chromium WebRTC sources): 

* https://webrtc.org/native-code/ios/ 

   These guys maybe having iOS demo for their AppRTC application. [e.g.](https://github.com/ISBX/apprtc-ios)

_PS. Phonegap/Cordova are easier-to-use webview solutions (android/iOS/etc.)._

**Comment by shaitkhan786** [comment]
Is it easy to write in React Native for WebRTC iOS functions?

**Comment by rayj00** [comment]
I am waiting for Apple to fix Safari with WebRTC capabilities.  They are working on it but no telling how long it will take for a stable WebRTC on iOS.

**Comment by shenguanjiejie** [comment]
Sorry for my foolish,let's close this issue ...
