### ISSUE TITLE
Admin-Guest Demo

### ISSUE THREAD

**Issue by marke123** [muaz-khan/WebRTC-Experiment#417]
You have an admin-guest.html demo for v2.2.2,  do you have something like that for v3.0? 

What I need to do is set up an audio chat with 2 rooms: Screening room and Main room. In the screening room will be a "screening person" who screens callers to see who they are and why they want to join (by talking to them over the audio chat in the screening room). In the main room will be a host person as the person hosting the broadcast.  When screener decides to accept the caller into the main audio chat then the screener will click a button to send a control message to move the caller from the screening room to the main room. 

Any basic sample code on how to accomplish that with v3.0 of your RTCMultiConnection libs?  Or maybe a different lib would work better?

**Comment by snuggs** [comment]
This issue can be closed as it is satisfied with https://github.com/muaz-khan/RTCMultiConnection/commit/e227d482c03b982f4e0741255c583230d35ee818 @muaz-khan /cc @marke123
