### ISSUE TITLE
Misleading README

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [muaz-khan/WebRTC-Experiment#449]
The README says:

-These demos/experiments are entirely client-side; i.e. no server installation needed!
-You can use all these demos in PHP/Python/Ruby/ASP.NET/etc. everywhere!

These point are contradictory! If you say there is no installation needed, most people assume you only need to host the HTML/JS/CSS files somewhere. If no installation is needed, why would you need any of the server-side languages mentioned?

**Comment by muaz-khan** [comment]
1. 90% of the demos uses Firebase or PubNub (3rd party free signaling services).
2. All demos uses free STUN servers from Google.

### Now the only remaining part is HTML over HTTPs.

You can take any HTML demo, upload on Google Drive or DropBox or any HTML_ONLY service; and I promise all of them will work!

Which means that:

> You can copy/download any HTML file; try on jsfiddle or jsbin or any similar free HTML editing services; and ALL THOSE DEMOS will work.

### NONE of those (90%) demos will request you install ANYTHING.

----

## Conclusion

1. You are **NOT requested** to install XMPP or Socket.io or setup WebSockets
2. You are **NOT requested** to setup STUN or TURN servers
3. You are **ONLY requested** to download HTML, and run on any HTTPs domain; and that's it.

----

## PS. _This repository is OPEN_SOURCED. Which means that you can modify README file and make a PULL request; and I always welcome contributions._

**Comment by hubertgrzeskowiak** [comment]
Thanks for the clarification. I've updated the README in PR #450
