### ISSUE TITLE
Example won't work on localhost. 

### ISSUE THREAD

**Issue by jonalbertini** [muaz-khan/WebRTC-Experiment#482]
hi, 
i'm trying your example, but after cloning it, I've only this error:

> Make sure that you are using Firefox Nightly and you enabled: media.getusermedia.screensharing.enabled flag from about:config page. You also need to add your domain in "media.getusermedia.screensharing.allowed_domains" flag.

I tried with your extension, and with a customized version. even on an other domain (ex : mydomain.com ) configured in extension I get the same result. to "emulate" the domain I use my /etc/hosts file.

I may missed something...

**Comment by muaz-khan** [comment]
Screen-Capturing on Firefox seems requires **HTTPs** even on LocalHost.

**Comment by jonalbertini** [comment]
All right, I works better now . 
sorry for that, and thank you a lot !
