### ISSUE TITLE
MediaStreamRecorder.getBlob() is missing?

### ISSUE THREAD

**Issue by bumi001** [muaz-khan/WebRTC-Experiment#490]
Hi, This is an excellent package. I was reading the code and noticed that MRecordRTC.getBlob() calls audioRecorder.getBlob(), videRecorder.getBlob() and gifRecorder.getBlob(). However, MediaStreamRecorder.getBlob() is not defined. It is a simple function to define. But, I thought I will bring it to your attention.

**Comment by muaz-khan** [comment]
It is RecordRTC level function, however you can easily define it as well: [dev/MediaStreamRecorder.js](https://github.com/muaz-khan/RecordRTC/blob/master/dev/MediaStreamRecorder.js):

```javascript
this.getBlob = function() {
    return this.blob;
};
```

Or in your HTML file (without modifying the MediaStreamRecorder.js):

```javascript
MediaStreamRecorder.prototype.getBlob = function() {
    return this.blob;
};
```

**Comment by bumi001** [comment]
Oh! You are right.  Thank you.
