### ISSUE TITLE
Change bitrate in MRecordRTC

### ISSUE THREAD

**Issue by vrajroham** [muaz-khan/WebRTC-Experiment#503]
How do I change `bitrate / VideoBitsPerSecond etc.` in MRecordRTC? I want to use it in [this](https://github.com/muaz-khan/WebRTC-Experiment/tree/master/RecordRTC/MRecordRTC) example.

https://github.com/muaz-khan/WebRTC-Experiment/tree/master/RecordRTC/MRecordRTC

**Comment by muaz-khan** [comment]
Please submit an issue here:

* https://github.com/muaz-khan/RecordRTC/issues

PS. **Is it recommended to use `RecordRTC` instead**.

```javascript
var options = {
  mimeType 'video/webm', // or video/mp4 or audio/ogg
  bitsPerSecond: 128000
};
var recorder = RecordRTC(mediaStream, options);
```

* https://github.com/muaz-khan/RecordRTC#bitspersecond
