### ISSUE TITLE
DOMException: The play() request was interrupted by a call to pause()

### ISSUE THREAD

**Issue by liujiaxiang** [muaz-khan/WebRTC-Experiment#505]
Hi, muaz, when I join a room, I used to have this problem, and can't see the video.
Have you ever been in this situation？

thank you!

**Comment by shah-smit** [comment]
@liujiaxiang I think I have been to this situation. I think its because you are calling `.play()` before the video is in DOM. Could you share your code snippet of adding video to the DOM video tag?

**Comment by liujiaxiang** [comment]
@shah-smit Here is my code:
        var div = document.createElement("div");
   	div.className="video-div";
   	div.id=event.streamid;
   	div.appendChild(mediaElement);
   				
       var h2 = document.createElement("h2");
       h2.innerHTML = event.extra.nickName;
       div.appendChild(h2);
                
        connection.videosContainer.appendChild(div);
        setTimeout(function() {
                    mediaElement.media.play();
                }, 5000);

**Comment by shah-smit** [comment]
@liujiaxiang Just wondering why are you adding 5 seconds to play?

**Comment by liujiaxiang** [comment]
@shah-smit I Just use the demo, here is no problem. When some user join the room,they can't see the video. here is my connection.session:
```
connection.session = {
				audio: true,
				video: true,
				//screen: true,
				data:true,
				## oneway: true
			};
```
Do you have a running demo in this case? thank you!

**Comment by liujiaxiang** [comment]
@shah-smit 
I think i find the problem,because i use one RTCMultiConnection to do anything. But my code of text chat has problem. Now, i use two RTCMultiConnection to do these things.
