### ISSUE TITLE
[Question] How to use mp4 instead of webm?

### ISSUE THREAD

**Issue by akshay-hazari** [muaz-khan/WebRTC-Experiment#524]
I tried to change the extension everywhere from webm to mp4 but it results in a broken mp4 file. 
I have to use it with OpenCV ,  works with files converted from webm to mp4 but takes a long time to convert.

While the webm file generated results in `(ERROR)icvOpenAVI_XINE(): Unable to open source demo.webm` which is expected since it doesn't work with webm files. 

And the mp4 output from javascript results in a broken mp4 file 
```
(ERROR)icvOpenAVI_XINE(): Unable to open source ' demo_6.mp4'
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f45c80a5fe0] moov atom not found
```

Any help with this will be really appreciated.

**Comment by balaraju1278** [comment]
Usually browsers won't support mp4 files

**Comment by DavidManoa9** [comment]
Is there any way around instead of recording webm. I want to record MP4 or MOV
