### ISSUE TITLE
How can I change signaling server to my own one?

### ISSUE THREAD

**Issue by norshtein** [muaz-khan/WebRTC-Experiment#540]
I'd like to change signaling server running at https://webrtcweb.com:9559/ to my own one.Is there any source code running at https://webrtcweb.com:9559/?

**Comment by tryshchenko** [comment]
@norshtein Actually, it can be implemented very easy, it's a transparent Websocket bridge between users. I can contribute it to this repo or create a new one if someone is interested in.

**Comment by muaz-khan** [comment]
Here is the source code:

* https://github.com/muaz-khan/WebRTC-Experiment/tree/master/socketio-over-nodejs
