### ISSUE TITLE
socketio-over-nodejs

### ISSUE THREAD

**Issue by yuledev** [muaz-khan/WebRTC-Experiment#589]
Hi,
Can you please update socketio-over-nodejs code in order to make it work with RTCMultiConnection v3.4.4?

**Comment by muaz-khan** [comment]
RTCMultiConnection v3.4.4 has its own built-in socket.io server.

```sh
mkdir test
cd test
git clone https://github.com/muaz-khan/RTCMultiConnection.git ./
node server.js
```

Now open port 9001. E.g.

```sh
http://localhost:9001/
http://127.0.0.1:9001/
```

Please check this for more info:

* [docs/installation-guide.md](https://github.com/muaz-khan/RTCMultiConnection/blob/master/docs/installation-guide.md)

----

#### To go in deep

The built-in server requires only two files:

1. [server.js](https://github.com/muaz-khan/RTCMultiConnection/blob/master/server.js)
2. [Signaling-Server.js](https://github.com/muaz-khan/RTCMultiConnection/blob/master/Signaling-Server.js)

**Comment by yuledev** [comment]
Thank you so much! :+1:
