### ISSUE TITLE
grunt-contrib-watch

### ISSUE THREAD

**Issue by GuusDeGraeve** [muaz-khan/WebRTC-Experiment#609]
I noticed RecordRTC has only one npm dependency which is 'grunt-contrib-watch'. Is there a reason for this? Other grunt plugins used by RecordRTC are nicely listed in the devDependencies but this one isn't. Is this an oversight?

**Comment by muaz-khan** [comment]
It was a mistake that was fixed YESTERDAY: https://github.com/muaz-khan/RecordRTC/commit/3b2609a8fa6c8a726486733d48ed1aa35f8071fd

NPM was updated as well:
* https://www.npmjs.com/package/recordrtc

Please try `npm install recordrtc` to download the latest version.
