### ISSUE TITLE
[websocket-over-nodejs] signaler.js, ssl.js and simple.js files missing

### ISSUE THREAD

**Issue by arthurmougin** [muaz-khan/WebRTC-Experiment#614]
Hi, 
in the documentation, you mention a couple of files that aren't present in the repo.
can you add them, please :)

edit : the files are mentionned there : https://github.com/muaz-khan/WebRTC-Experiment/blob/master/websocket-over-nodejs/README.md

**Comment by muaz-khan** [comment]
You can try [`server.js`](https://github.com/muaz-khan/WebRTC-Experiment/blob/master/websocket-over-nodejs/server.js) instead:

```sh
node server.js
```

Now open `https://localhost:9449/`.

You can modify SSL keys [here](https://github.com/muaz-khan/WebRTC-Experiment/blob/master/websocket-over-nodejs/server.js#L14):

```javascript
var options = {
    key: fs.readFileSync('fake-keys/privatekey.pem'),
    cert: fs.readFileSync('fake-keys/certificate.pem')
    // key: fs.readFileSync('/etc/letsencrypt/live/webrtcweb.com/privkey.pem'),
    // cert: fs.readFileSync('/etc/letsencrypt/live/webrtcweb.com/fullchain.pem')
};
```

I'll fix `readme.md` soon.

**Comment by rajhlinux** [comment]
I'm getting this error:

![Screen Shot 2020-03-09 at 10 37 09 PM](https://user-images.githubusercontent.com/61344181/76274261-8ec1da80-6256-11ea-9c59-b581ec580058.png)
