### ISSUE TITLE
SSL (HTTPS Socket.io)

### ISSUE THREAD

**Issue by epexa** [muaz-khan/WebRTC-Experiment#62]
How do I convert socket.io to make it work on HTTPS?

RTCMultiConnection.js:

<pre>
<code>var SIGNALING_SERVER = 'https:/domain.com:8888/';
var socket = io.connect(SIGNALING_SERVER + channel, {secure:true});</code>
</pre>

signaler.js

HTTP version:

<pre>
<code>var app = require('express')(),
    server = require('http').createServer(app),
    io = require('socket.io').listen(server);
server.listen(8888);</code>
</pre>

HTTPS version:

<pre>
<code>var app = require('express')(),
    fs = require('fs'),
    options = {
        pfx: fs.readFileSync('secure.pfx'),
        requestCert: true
    }
    server = require('https').createServer(options, app).listen(8888),
    io = require('socket.io').listen(server);</code>
</pre>

Does not work!

Help please!

**Comment by NerdAlsoRan** [comment]
I am trying to connect node.js server with socket.io using ssl. My server has windows 2008 server and iis installed. I intalled ssl my domain name on IIS and I can connect with my domain via http s://mydomain.com. But I cant connect my node.js server with ssl. I am using following code on my server,Have you got any ideas what the problem might be?

  var fs =    require('fs');

  var options = {
  pfx: fs.readFileSync('sslkey.pfx'),
  passphrase:'password'
    };

    var express = require('express'),
        app = express(),
        server = require('https').createServer(options,app),    
        server2 = require('http').createServer(app),    
        io = require('socket.io').listen(server, {log: true});

    function sendCrossDomain(req, res){
    //return;
        res.set('Content-Type', 'text/xml; charset=utf-8');
        res.sendfile(__dirname + '/crossdomain-test.xml');
    };

    app.get('/crossdomain.xml', sendCrossDomain);
    app.get('/', sendCrossDomain);

    server.listen(9595);

**Comment by Alejandroalh** [comment]
I'm trying to change the audio codec on your experiment for performace studies, where is the SDP offer created or how would you change the audio codec Muaz?

**Comment by imrizwan89** [comment]
I am trying to run HTTPs server
node signaler-ssl.js
getting error
Error: Cannot find module '/home/ec2-user/signaler-ssl.js'

however 
node signale.js working fine

**Comment by jefersoncunha** [comment]
@muaz-khan  how can i deploy on heroku.com using it?

**Comment by sehrishabdul** [comment]
Hi,

I'm trying to use socket.io with https. Client is unable to connect to the server. Below is my code for server and client

Server.js
var express = require('express');
var app = express();
var fs = require('fs');
var https = require('https');



var options = {
        key: fs.readFileSync('certificates/apache-selfsigned.key'),
        cert: fs.readFileSync('certificates/apache-selfsigned.crt')
};
var serverPort = 3000;

var server = https.createServer(options, app);
var io = require('socket.io')(server);

app.get('/', function(req, res) {
  res.sendFile(__dirname + '/index.html');
});

io.on('connection', function(socket) {
  console.log('new connection');
});

server.listen(serverPort, function() {
  console.log('server up and running at %s port', serverPort);
});

Client.html
<html>

  <head>

  </head>
  <body>
    <h1>I am alive!!</h1>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.4/socket.io.js"></script>

    <script>
      var URL_SERVER = 'https://domain.com:3000';
      var socket = io.connect(URL_SERVER,{secure: true});

      socket.on('message', function(data) {
        alert(data);
      });
    </script>
  </body>

</html>

Help would be graetly appreciated

**Comment by aswinrathees** [comment]
Hi Muaz Khan,
I am facing the following issue in my terminal after running node signaler-ssl.js.Eventhough the socket.io is started,it gives the following in terminal
setting poll timeout
debug - discarding transport
debug - cleared close timeout for client 34kfyFKPyFsRShXb012q

**Comment by aswinrathees** [comment]
Hi,i am running webrtc-experiment in ubuntu 18.I have openssl for node as well.But while performing broadcast from other machine i am getting a machine discarding transport and hence not able to view broadcast from another machine.
