### ISSUE TITLE
Mute/UnMute audio, video

### ISSUE THREAD

**Issue by epexa** [muaz-khan/WebRTC-Experiment#68]
There is a function:

``` javascript
connection.streams['stream-id'].mute({audio: true});
```

this function disables the output sound, then there are other people I hear.

How can I disable the transmission of sound or video? What would other people have not heard of.

And then engage the gear back?

**Comment by aamodbrainvire** [comment]
@muaz-khan how to mute stream for specific user,
example:-
we have 3 participants but i don't want to share screen to 3 users in that scenario how can i do that

**Comment by Sharanagouda** [comment]
Its giving an error : cannot read property 'mute 'of undefined I an developing it for mobile device

**Comment by xujingzhou** [comment]
How should Mute be used with the latest version?
